version: "3.5"
services:
  reverse-proxy:
    container_name: traefik
    hostname: traefik.${TOP_LEVEL_DOMAIN}
    image: ${TRAEFIK_DOCKER_IMAGE}
    restart: always
    command:
      - --log.level=DEBUG # on for testing
      - --api.insecure=${TRAEFIK_API_INSECURE_ENABLED}
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=${TRAEFIK_LETSENCRYPT_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json

      - --tls.options.default.minversion=VersionTLS13
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ${BASE_DATA_LOCATION}/proxy/traefik.yaml:/etc/traefik.yaml
      - ${BASE_DATA_LOCATION}/letsencrypt/acme.json:/letsencrypt/acme.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.${TOP_LEVEL_DOMAIN}`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.tls.certresolver=myresolver
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.services.dashboard.loadbalancer.server.port=8080

      - traefik.http.middlewares.fwd-auth-google-mdl.forwardAuth.address=http://forwardauth:4181
      - traefik.http.middlewares.fwd-auth-google-mdl.forwardAuth.authResponseHeaders=X-Forwarded-User
      - traefik.http.middlewares.fwd-auth-google-mdl.forwardAuth.trustForwardHeader=true
    networks:
      - web

  forwardauth:
    container_name: fwd-auth-google
    hostname: fwd-auth-google
    image: thomseddon/traefik-forward-auth:2.2
    restart: unless-stopped
    networks:
      - web
    environment:
      - CLIENT_ID=$GOOGLE_CLIENT_ID
      - CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - SECRET=$OAUTH_SECRET
      - COOKIE_DOMAIN=$TOP_LEVEL_DOMAIN
      - AUTH_HOST=oauth.$TOP_LEVEL_DOMAIN
      - WHITELIST=$TRAEFIK_LETSENCRYPT_EMAIL
      - INSECURE_COOKIE=false
      - LOG_LEVEL=debug
      - LOG_FORMAT=pretty
      - LIFETIME=15 # Short for testing
    expose:
      - 4181
    labels:
      - traefik.http.routers.oauth.rule=Host(`oauth.${TOP_LEVEL_DOMAIN}`)
      - traefik.http.routers.oauth.entrypoints=websecure
      - traefik.http.routers.oauth.tls.certresolver=myresolver
      - traefik.http.routers.oauth.middlewares=fwd-auth-google-mdl

  whoami:
    container_name: whoami
    hostname: whoami
    image: containous/whoami
    networks:
      - web
    labels:
      - traefik.http.routers.whoami-rtr.rule=Host(`whoami.${TOP_LEVEL_DOMAIN}`)
      - traefik.http.routers.whoami-rtr.entrypoints=websecure
      - traefik.http.routers.whoami-rtr.tls.certresolver=myresolver
      - traefik.http.routers.whoami-rtr.middlewares=fwd-auth-google-mdl
    depends_on:
      - reverse-proxy
      - forwardauth

  website:
    container_name: nginx
    hostname: www.${TOP_LEVEL_DOMAIN}
    image: nginx:alpine
    restart: always
    expose:
      - 80
    networks:
      - web
    volumes:
      - ${BASE_DATA_LOCATION}/website:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`${TOP_LEVEL_DOMAIN}`, `www.${TOP_LEVEL_DOMAIN}`)"
      - "traefik.http.routers.website.tls.certresolver=myresolver"
      - "traefik.http.routers.website.entrypoints=websecure"
    depends_on:
      - reverse-proxy

  rss-reader:
    container_name: ttrss
    hostname: rss.${TOP_LEVEL_DOMAIN}
    image: wangqiru/ttrss:19.8
    restart: unless-stopped
    expose:
      - 181
    networks:
      - web
      - data
    environment:
      - DB_HOST=rss-db
      - DB_PORT=5432
      - DB_NAME=${TTRSS_POSTGRES_DB}
      - DB_USER=${TTRSS_POSTGRES_USER}
      - DB_PASS=${TTRSS_POSTGRES_PASSWORD}
      - SELF_URL_PATH=https://rss.${TOP_LEVEL_DOMAIN}/
      # - ENABLE_PLUGINS=auth_internal,fever
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.ttrss.tls=true
      - traefik.http.routers.ttrss-secure.tls.certresolver=myresolver
      - traefik.http.routers.ttrss-secure.entrypoints=websecure
      - traefik.http.routers.ttrss-secure.rule=Host(`rss.${TOP_LEVEL_DOMAIN}`)
    depends_on:
      - reverse-proxy
      - rss-db
    command: sh -c 'sh /wait-for.sh $$DB_HOST:$$DB_PORT -- php /configure-db.php && exec s6-svscan /etc/s6/'

  rss-db:
    image: postgres:alpine
    container_name: rss-db
    hostname: rss-db
    restart: unless-stopped
    expose:
      - 5432
    volumes:
      - ${TTRSS_HOST_DB_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${TTRSS_POSTGRES_DB}
      - POSTGRES_USER=${TTRSS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TTRSS_POSTGRES_PASSWORD}
    networks:
      - data

  cloud-db:
    container_name: pg-cloud
    hostname: cloud-db
    image: ${NEXTCLOUD_POSTGRES_DOCKER_IMAGE}
    restart: unless-stopped
    expose:
      - 5432
    volumes:
      - ${NEXTCLOUD_HOST_DB_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NEXTCLOUD_POSTGRES_DB}
      - POSTGRES_USER=${NEXTCLOUD_POSTGRES_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_POSTGRES_PASSWORD}
    networks:
      - data

  cloud:
    depends_on:
      - cloud-db
      - reverse-proxy
    image: ${NEXTCLOUD_DOCKER_IMAGE}
    container_name: nextcloud
    hostname: ${NEXTCLOUD_FQDN}
    volumes:
      - ${NEXTCLOUD_HOST_WEB_DIR}:/var/www/html
      # changing the data directory leads to permissions issues for www-data user - not sure how to resolve.
      # - ${NEXTCLOUD_HOST_DATA_DIR}:/var/www/data
    networks:
      - data
      - web
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=cloud-db
      - POSTGRES_DB=${NEXTCLOUD_POSTGRES_DB}
      - POSTGRES_USER=${NEXTCLOUD_POSTGRES_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_POSTGRES_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_FQDN}
      - TRUSTED_PROXIES=${DOCKER_SUBNET_CIDR}
      # - NEXTCLOUD_DATA_DIR=/var/www/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud-secure.tls.certresolver=myresolver
      - traefik.http.routers.nextcloud-secure.entrypoints=websecure
      - traefik.http.routers.nextcloud-secure.rule=Host(`${NEXTCLOUD_FQDN}`)
      - traefik.http.routers.nextcloud-secure.middlewares=nextcloud,nextcloud_redirect
      # This resolves security warnings in Admin settings
      - traefik.http.middlewares.nextcloud.headers.stsSeconds=15552001
      # Resolves warning about X-Frame-Options header
      - traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=SAMEORIGIN
      # These 2 resolves issues handling calendar and vCards
      - traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=/remote.php/dav/
      # These 2 resolve leaky server information
      - traefik.http.middlewares.nextcloud.headers.customresponseheaders.Server=
      - traefik.http.middlewares.nextcloud.headers.customresponseheaders.X-Powered-By=

      # This middleware breaks trust due to mixed content (tested Chrome 84 and Firefox 80). It does correct the redirect for logging in though.
      # - "traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' ${TOP_LEVEL_DOMAIN} *.${TOP_LEVEL_DOMAIN}"
      # These remaining ones I'm not quite sure what they're supposed to resolve.
      # - traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=ALLOW-FROM https://${NEXTCLOUD_FQDN}
      # Some of these look like security enhancements
      # - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
      # - traefik.http.middlewares.nextcloud.headers.stsPreload=true
      # - traefik.http.middlewares.nextcloud.headers.browserXSSFilter=true
      # - traefik.http.middlewares.nextcloud.headers.contentTypeNosniff=true
      # - traefik.http.middlewares.nextcloud.headers.forceSTSHeader=true
      # - traefik.http.middlewares.nextcloud.headers.referrerPolicy=no-referrer

networks:
  web:
    name: web
  data:
    name: data
