
CREATE USER "${POSTGRES_USER}" WITH PASSWORD "${POSTGRES_PASSWORD}";
CREATE DATABASE "${POSTGRES_DB}" TEMPLATE template0 ENCODING 'UNICODE';
ALTER DATABASE "${POSTGRES_DB}" OWNER TO "${POSTGRES_USER}";
GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_DB}" TO "${POSTGRES_USER}";
