
version: "3.7"
services:
  traefik:
    image: traefik:v2.2.1
    restart: always
    container_name: "traefik"
    hostname: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
      - 443:443
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      - /opt/traefik/acme.json:/acme.json
    container_name: traefik
networks:
    default:
        external:
          name: $DEFAULT_NETWORK

    # networks:
    #   proxy:
    #     external: true