#!/bin/bash

# Simple git hook to prevent invalid YAML commits

YAML_FILES=$( find . -name "*.y*ml" )
for YAML_FILE in $YAML_FILES
do
  yamllint --no-warnings $YAML_FILE
  CODE=$?
  [ $CODE -ne 0 ] && exit $CODE
done
exit 0